server:
  port: 8001

spring:
  application:
    name: cloud_provider_payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wang



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wang.springcloud.entities  # 所有Entity 别名类所在包